const list = [
  {
    id: 1,
    title: "My First Book of Pencil Control",
    author: "by Wonder House Books | 25 April 2018",
    price: 109.95,
    category: "bag",
    img: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "108 Panchatantra Stories",
    author: "by Maple Press  | 1 September 2020",
    price: 22.3,
    img: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    category: "men",
    amount: 1,
  },
  {
    id: 3,
    title: "Amazing Questions & Answers Science",
    author: "by Om Books Editorial Team  | 25 November 2018",
    category: "men",
    price: 55.99,
    img: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "My First Book of Pencil Control",
    category: "jewellery",
    author: "by Wonder House Books | 25 April 2018",
    price: 695,
    img: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    amount: 1,
  },
  {
    id: 5,
    category: "women",
    title: "My First 1000 Words",
    author: "by Wonder House Books  | 1 January 2018",
    price: 29.95,
    img: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "101 Panchatantra Stories for Children",
    author: "by Om Books Editorial Team | 30 September 2020",
    category: "jewellery",
    price: 168,
    img: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Pre-School Activities Pack ",
    author: "by Om Books Editorial Team  | 1 January 2021",
    category: "women",
    price: 12.99,
    img: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Early Learning Library Pack 1",
    author: "by Wonder House Books  | 6 December 2020",
    price: 9.99,
    category: "jewellery",
    img: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Blossom Moral Story Book for Kids ",
    author: "by Content Team at Target Publications",
    category: "jewellery",
    price: 10.99,
    img: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Brain Activity Book for Kids",
    author: "by Maple Press | 1 September 2021",
    category: "Device",
    price: 64,
    img: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Willy the Silly Panda",
    author: "by Rebecca Smith  | 14 December 2021",
    category: "Device",
    price: 109,
    img: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Grandma's Bag of Stories",
    author: "by Sudha Murty | 1 January 2015",
    category: "Device",
    price: 106,
    img: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    amount: 1,
  },
];

export default list;
